export type ToolMode =
  | 'select'
  | 'addText'
  | 'addSignature'
  | 'addImage'
  | 'addCode'
  | 'drawArrow'
  | 'drawRect'
  | 'drawEllipse'
  | 'drawFreehand'
  | 'drawHighlight'
  | 'addComment'
  | 'drawRedaction'
  | 'drawErase'
  | 'editText'
  | 'fillBucket'
  | 'crop'
  | 'signRect';
